## Some tests of Airy()


test_that("the Airy suite behaves itself", {
    expect_true(TRUE)
    tol <- 1e-12

    vals_airy_Ai_mathematica <-   # generated by N[AiryAiZero[Range[10]], digits = 16]
        c(
            -2.338107410459767, -4.087949444130971, -5.520559828095551,
            -6.786708090071759, -7.944133587120853, -9.022650853340980,
            -10.04017434155809, -11.00852430373326, -11.93601556323626,
            -12.82877675286576)

    vals_airy_Ai_gsl <- airy_zero_Ai(seq_len(10))
    expect_true(all(abs(vals_airy_Ai_mathematica - vals_airy_Ai_gsl) < tol))


    vals_airy_Bi_mathematica <-       # generated by N[AiryBiZero[Range[10]], digits = 16]
        c(
            -1.173713222709128, -3.271093302836353, -4.830737841662016,
            -6.169852128310251, -7.376762079367764, -8.491948846509388,
            -9.538194379346239, -10.52991350670536, -11.47695355127878,
            -12.38641713858274)
    
    vals_airy_Bi_gsl <- airy_zero_Bi(seq_len(10))
    expect_true(all(abs(vals_airy_Bi_mathematica - vals_airy_Bi_gsl) < tol))
    
    ## There does not seem to be a native airyAiPrimeZero[] function
    ## in mathematica.  Using 
    
    ## NSolve[{AiryAiPrime[x] == 0  , x < -1  , x > -2}, Reals, digits = 16]
    ## NSolve[{AiryAiPrime[x] == 0  , x < -3  , x > -4}, Reals, digits = 16]
    ## NSolve[{AiryAiPrime[x] == 0  , x < -4  , x > -5}, Reals, digits = 16]

    vals_airy_Ai_deriv_mathematica <-
        c(
            -1.018792971647471,  -3.248197582179837, -4.820099211178736)
    
    vals_airy_Ai_deriv_gsl <- airy_zero_Ai_deriv(1:3)
    expect_true(all(abs(vals_airy_Ai_deriv_mathematica - vals_airy_Ai_deriv_gsl) < tol))


    ## NSolve[{AiryBiPrime[x] == 0  , x < -2  , x > -3}, Reals, digits = 16]
    ## NSolve[{AiryBiPrime[x] == 0  , x < -4  , x > -5}, Reals, digits = 16]
    ## NSolve[{AiryBiPrime[x] == 0  , x < -5  , x > -6}, Reals, digits = 16]

    vals_airy_Bi_deriv_mathematica <-
        c(
            -2.294439682614123, -4.073155089071828, -5.512395729663599)
    
    vals_airy_Bi_deriv_gsl <- airy_zero_Bi_deriv(1:3)
    expect_true(all(abs(vals_airy_Bi_deriv_mathematica - vals_airy_Bi_deriv_gsl) < tol))


} )
