#include <gsl/gsl_sf_clausen.h>
#include <gsl/gsl_errno.h>

/* function names generated by removing  "gsl_sf" from the beginning
   of the name.  Thus gsl_sf_dawson  goes to dawson. */


void clausen_e(const double *x, const int *len, double *val, double *err, int *status)
{
	int i;
	gsl_sf_result result;
	gsl_set_error_handler_off();
  
	for(i = 0; i< *len ; i++){
		status[i] = gsl_sf_clausen_e(x[i], &result) ;
		val[i] = result.val;
		err[i] = result.err;
	}
}  
