#include <gsl/gsl_sf_transport.h>
#include <gsl/gsl_errno.h>

/* function names generated by removing  "gsl_sf" from the beginning
   of the name.  Thus gsl_sf_transport  goes to transport. */


void transport_2(const double *x, const int *len, double *val, double *err, int *status)
{
	int i;
	gsl_sf_result result;
	gsl_set_error_handler_off();
  
	for(i = 0; i< *len ; i++){
		status[i] = gsl_sf_transport_2_e(x[i], &result) ;
		val[i] = result.val;
		err[i] = result.err;
	}
} 
 
void transport_3(const double *x, const int *len, double *val, double *err, int *status)
{
	int i;
	gsl_sf_result result;
	gsl_set_error_handler_off();
  
	for(i = 0; i< *len ; i++){
		status[i] = gsl_sf_transport_3_e(x[i], &result) ;
		val[i] = result.val;
		err[i] = result.err;
	}
} 
 
void transport_4(const double *x, const int *len, double *val, double *err, int *status)
{
	int i;
	gsl_sf_result result;
	gsl_set_error_handler_off();
  
	for(i = 0; i< *len ; i++){
		status[i] = gsl_sf_transport_4_e(x[i], &result) ;
		val[i] = result.val;
		err[i] = result.err;
	}
}  

void transport_5(const double *x, const int *len, double *val, double *err, int *status)
{
	int i;
	gsl_sf_result result;
	gsl_set_error_handler_off();
  
	for(i = 0; i< *len ; i++){
		status[i] = gsl_sf_transport_5_e(x[i], &result) ;
		val[i] = result.val;
		err[i] = result.err;
	}
}  
