# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# for debugging help, https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master]

name: R-CMD-check-gsl

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/setup-tinytex@v2

      - run: tlmgr install scheme-full
      - run: tlmgr install wrapfig
      - run: tlmgr install doublestroke
      - run: tlmgr install bbm
      - run: tlmgr install bbm-macros
      - run: tlmgr install wasysym
      - run: tlmgr install yfonts
      - run: tlmgr install grfext
      - run: tlmgr install cm-super

      - run: |
          sudo apt-get update
          sudo apt-get install -y pandoc-citeproc

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--compact-vignettes=both")'
